"""Ensemble learning wrappers."""

from sklearn_mastery.models.ensemble.ensemble_methods import (
    BOOSTING_ALGORITHMS,
    HAS_LIGHTGBM,
    HAS_XGBOOST,
    BaggingEnsemble,
    BlendingEnsemble,
    BoostingEnsemble,
    EnsembleAnalyzer,
    EnsembleMethods,
    StackingEnsemble,
    VotingEnsemble,
    agreement_rate,
    correlation_coefficient,
    disagreement_measure,
    diversity_matrix,
    double_fault_measure,
    entropy_measure,
    kohavi_wolpert_variance,
    pairwise_diversity,
    q_statistic,
)

__all__ = [
    "BOOSTING_ALGORITHMS",
    "HAS_LIGHTGBM",
    "HAS_XGBOOST",
    "BaggingEnsemble",
    "BlendingEnsemble",
    "BoostingEnsemble",
    "EnsembleAnalyzer",
    "EnsembleMethods",
    "StackingEnsemble",
    "VotingEnsemble",
    "agreement_rate",
    "correlation_coefficient",
    "disagreement_measure",
    "diversity_matrix",
    "double_fault_measure",
    "entropy_measure",
    "kohavi_wolpert_variance",
    "pairwise_diversity",
    "q_statistic",
]
