"""Ensemble learning wrappers and diversity analysis utilities.

This module provides scikit-learn compatible meta-estimators that combine
several base learners:

* :class:`VotingEnsemble` -- hard/soft majority voting (classification) or
  weighted averaging (regression) over a list of ``(name, estimator)`` pairs.
* :class:`BaggingEnsemble` -- bootstrap aggregation of a single base learner
  with sample/feature subsampling and out-of-bag scoring.
* :class:`BoostingEnsemble` -- unified wrapper around AdaBoost, gradient
  boosting, histogram gradient boosting and (optionally) XGBoost / LightGBM.
* :class:`StackingEnsemble` -- stacked generalisation with out-of-fold
  meta-features generated by cross-validation.
* :class:`BlendingEnsemble` -- stacked generalisation with meta-features
  generated on a single hold-out split.

All wrappers follow the scikit-learn estimator contract: constructor
arguments are stored verbatim (so :func:`sklearn.base.clone` works), ``fit``
returns ``self`` and fitted attributes end with an underscore.  Every wrapper
can be persisted with :meth:`save_model` and restored with :meth:`load_model`.

:class:`EnsembleMethods` is a convenience factory used throughout the
examples, and the module-level diversity measures (Q-statistic, disagreement,
double-fault, Kohavi-Wolpert variance, ...) together with
:class:`EnsembleAnalyzer` support quantitative analysis of *why* an ensemble
helps.

Optional dependencies (``xgboost``, ``lightgbm``) are guarded by the
``HAS_XGBOOST`` and ``HAS_LIGHTGBM`` flags; the module imports without them.
"""

from __future__ import annotations

import inspect
from pathlib import Path
from typing import Any, Dict, Iterator, List, Optional, Sequence, Tuple, Union

import joblib
import numpy as np
from scipy import sparse
from sklearn.base import BaseEstimator, clone, is_classifier, is_regressor
from sklearn.ensemble import (
    AdaBoostClassifier,
    AdaBoostRegressor,
    BaggingClassifier,
    BaggingRegressor,
    ExtraTreesClassifier,
    ExtraTreesRegressor,
    GradientBoostingClassifier,
    GradientBoostingRegressor,
    HistGradientBoostingClassifier,
    HistGradientBoostingRegressor,
    RandomForestClassifier,
    RandomForestRegressor,
)
from sklearn.linear_model import LinearRegression, LogisticRegression, Ridge
from sklearn.metrics import accuracy_score, r2_score
from sklearn.model_selection import KFold, StratifiedKFold, check_cv, cross_val_predict, train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.utils.multiclass import type_of_target
from sklearn.utils.parallel import Parallel, delayed
from sklearn.utils.validation import (
    check_array,
    check_consistent_length,
    check_is_fitted,
    column_or_1d,
    has_fit_parameter,
)

from sklearn_mastery.config.logging_config import LoggerMixin, get_logger

try:  # scikit-learn >= 1.6 tag system
    from sklearn.utils import ClassifierTags, RegressorTags

    HAS_SKLEARN_TAGS = True
except ImportError:  # pragma: no cover - exercised only on scikit-learn < 1.6
    ClassifierTags = None  # type: ignore[assignment,misc]
    RegressorTags = None  # type: ignore[assignment,misc]
    HAS_SKLEARN_TAGS = False

try:
    import xgboost as xgb

    HAS_XGBOOST = True
except ImportError:  # pragma: no cover - optional dependency
    xgb = None  # type: ignore[assignment]
    HAS_XGBOOST = False

try:
    import lightgbm as lgb

    HAS_LIGHTGBM = True
except ImportError:  # pragma: no cover - optional dependency
    lgb = None  # type: ignore[assignment]
    HAS_LIGHTGBM = False

logger = get_logger(__name__)

ArrayLike = Union[np.ndarray, Sequence[Any]]
EstimatorList = Sequence[Tuple[str, BaseEstimator]]

CLASSIFICATION = "classification"
REGRESSION = "regression"
AUTO = "auto"
_TASK_TYPES = (CLASSIFICATION, REGRESSION, AUTO)

BOOSTING_ALGORITHMS = ("adaboost", "gradientboosting", "histgradientboosting", "xgboost", "lightgbm")


# --------------------------------------------------------------------------- #
# Internal helpers
# --------------------------------------------------------------------------- #
def _check_X(X: ArrayLike, *, allow_nan: bool = True) -> Any:
    """Validate a feature matrix, tolerating NaN when the base learners allow it.

    Args:
        X: Feature matrix (dense or sparse).
        allow_nan: Whether NaN values are permitted.

    Returns:
        Validated 2-D array or sparse matrix.
    """
    finite: Union[bool, str] = "allow-nan" if allow_nan else True
    try:
        return check_array(X, dtype=None, accept_sparse=["csr", "csc"], ensure_all_finite=finite)
    except TypeError:  # pragma: no cover - scikit-learn < 1.6 keyword name
        return check_array(X, dtype=None, accept_sparse=["csr", "csc"], force_all_finite=finite)


def _check_X_y(X: ArrayLike, y: ArrayLike) -> Tuple[Any, np.ndarray]:
    """Validate ``X`` and ``y`` jointly."""
    X = _check_X(X)
    y = column_or_1d(y, warn=True)
    check_consistent_length(X, y)
    return X, y


def _target_task_type(y: ArrayLike) -> str:
    """Infer the learning task from the target vector.

    Args:
        y: Target vector.

    Returns:
        ``"classification"`` or ``"regression"``.

    Raises:
        ValueError: If the target type is not supported.
    """
    target = type_of_target(y)
    if target in ("binary", "multiclass"):
        return CLASSIFICATION
    if target == "continuous":
        return REGRESSION
    raise ValueError(f"Unsupported target type '{target}'; expected binary, multiclass or continuous.")


def _estimator_task_type(estimator: Any) -> Optional[str]:
    """Return the task type implied by an estimator, or ``None`` if unknown."""
    if estimator is None:
        return None
    if is_classifier(estimator):
        return CLASSIFICATION
    if is_regressor(estimator):
        return REGRESSION
    return None


def _validate_task_type(task_type: str) -> str:
    """Validate a ``task_type`` argument."""
    if task_type not in _TASK_TYPES:
        raise ValueError(f"task_type must be one of {_TASK_TYPES}, got {task_type!r}.")
    return task_type


def _validate_estimators(estimators: Any, argument: str = "estimators") -> List[Tuple[str, BaseEstimator]]:
    """Validate a list of ``(name, estimator)`` pairs.

    Args:
        estimators: Candidate list.
        argument: Name of the argument (used in error messages).

    Returns:
        The validated list.

    Raises:
        ValueError: If the list is empty, malformed, or names are not unique.
    """
    if estimators is None or len(estimators) == 0:
        raise ValueError(
            f"'{argument}' must contain at least one (name, estimator) pair; got {estimators!r}."
        )
    validated: List[Tuple[str, BaseEstimator]] = []
    names: List[str] = []
    for item in estimators:
        if not isinstance(item, (tuple, list)) or len(item) != 2:
            raise ValueError(f"Each element of '{argument}' must be a (name, estimator) tuple; got {item!r}.")
        name, estimator = item
        if not isinstance(name, str) or not name:
            raise ValueError(f"Estimator names must be non-empty strings; got {name!r}.")
        if estimator is None or not hasattr(estimator, "fit"):
            raise ValueError(f"Estimator '{name}' does not implement fit().")
        if "__" in name:
            raise ValueError(f"Estimator names must not contain '__'; got {name!r}.")
        names.append(name)
        validated.append((name, estimator))
    if len(set(names)) != len(names):
        raise ValueError(f"Estimator names must be unique; got {names}.")
    return validated


def _resolve_task_type(
    task_type: str,
    estimators: Sequence[Any],
    y: Optional[ArrayLike] = None,
) -> str:
    """Resolve ``task_type='auto'`` from the base estimators and/or the target.

    Args:
        task_type: Requested task type (``"auto"``, ``"classification"`` or ``"regression"``).
        estimators: Base estimators (used for inference and validation).
        y: Optional target used when the estimators are inconclusive.

    Returns:
        The resolved task type.

    Raises:
        ValueError: If the base estimators disagree with each other or with ``task_type``.
    """
    _validate_task_type(task_type)
    implied = {t for t in (_estimator_task_type(est) for est in estimators) if t is not None}
    if len(implied) > 1:
        raise ValueError(
            "Base estimators mix classifiers and regressors; all estimators must solve the same task. "
            f"Found: {[(type(est).__name__, _estimator_task_type(est)) for est in estimators]}"
        )
    if task_type != AUTO:
        if implied and task_type not in implied:
            raise ValueError(f"task_type={task_type!r} but base estimators are {implied.pop()} estimators.")
        return task_type
    if implied:
        return implied.pop()
    if y is not None:
        return _target_task_type(y)
    raise ValueError("Could not infer task type; pass task_type='classification' or 'regression'.")


def _fit_one(
    estimator: BaseEstimator, X: Any, y: np.ndarray, sample_weight: Optional[np.ndarray]
) -> BaseEstimator:
    """Fit a single (already cloned) estimator, forwarding ``sample_weight`` when supported."""
    if sample_weight is not None and has_fit_parameter(estimator, "sample_weight"):
        return estimator.fit(X, y, sample_weight=sample_weight)
    return estimator.fit(X, y)


def _filter_kwargs(estimator_cls: Any, kwargs: Dict[str, Any]) -> Dict[str, Any]:
    """Drop keyword arguments that ``estimator_cls`` does not accept (logging each drop)."""
    try:
        params = inspect.signature(estimator_cls.__init__).parameters
    except (TypeError, ValueError):  # pragma: no cover - C-implemented signatures
        return dict(kwargs)
    if any(p.kind is inspect.Parameter.VAR_KEYWORD for p in params.values()):
        return dict(kwargs)
    accepted: Dict[str, Any] = {}
    for key, value in kwargs.items():
        if key in params:
            accepted[key] = value
        else:
            logger.warning("Dropping unsupported parameter %r for %s.", key, estimator_cls.__name__)
    return accepted


def _hstack(blocks: Sequence[Any]) -> Any:
    """Horizontally stack dense and/or sparse blocks."""
    if any(sparse.issparse(b) for b in blocks):
        return sparse.hstack([sparse.csr_matrix(b) for b in blocks]).tocsr()
    return np.hstack([np.asarray(b) for b in blocks])


# --------------------------------------------------------------------------- #
# Base class
# --------------------------------------------------------------------------- #
class _BaseEnsemble(BaseEstimator, LoggerMixin):
    """Common scaffolding for the ensemble wrappers (tags, scoring, persistence)."""

    task_type: str

    # -- task-type aware scikit-learn tags ---------------------------------- #
    def _tags_task_type(self) -> Optional[str]:
        """Task type used for estimator tags; ``None`` when it cannot be determined."""
        fitted = getattr(self, "task_type_", None)
        if fitted is not None:
            return fitted
        declared = getattr(self, "task_type", AUTO)
        if declared in (CLASSIFICATION, REGRESSION):
            return declared
        try:
            return _resolve_task_type(AUTO, self._tag_estimators())
        except ValueError:
            return None

    def _tag_estimators(self) -> Sequence[Any]:
        """Estimators inspected to infer the task type before fitting."""
        return []

    @property
    def _estimator_type(self) -> Optional[str]:  # scikit-learn < 1.6
        task = self._tags_task_type()
        if task == CLASSIFICATION:
            return "classifier"
        if task == REGRESSION:
            return "regressor"
        return None

    def __sklearn_tags__(self):  # scikit-learn >= 1.6
        tags = super().__sklearn_tags__()
        task = self._tags_task_type()
        if HAS_SKLEARN_TAGS and task == CLASSIFICATION:
            tags.estimator_type = "classifier"
            tags.classifier_tags = ClassifierTags()
        elif HAS_SKLEARN_TAGS and task == REGRESSION:
            tags.estimator_type = "regressor"
            tags.regressor_tags = RegressorTags()
        return tags

    # -- generic API -------------------------------------------------------- #
    @property
    def is_classification_(self) -> bool:
        """Whether the fitted ensemble solves a classification task."""
        check_is_fitted(self, "task_type_")
        return self.task_type_ == CLASSIFICATION

    def score(self, X: ArrayLike, y: ArrayLike) -> float:
        """Accuracy (classification) or R^2 (regression) on ``(X, y)``.

        Args:
            X: Feature matrix.
            y: Ground-truth targets.

        Returns:
            The score.
        """
        y_pred = self.predict(X)
        if self.is_classification_:
            return float(accuracy_score(y, y_pred))
        return float(r2_score(y, y_pred))

    def save_model(self, filepath: Union[str, Path]) -> Path:
        """Persist the fitted ensemble with :mod:`joblib`.

        Args:
            filepath: Destination path (parent directories are created).

        Returns:
            The resolved path written to.

        Raises:
            sklearn.exceptions.NotFittedError: If the ensemble is not fitted.
        """
        check_is_fitted(self, "task_type_")
        path = Path(filepath)
        path.parent.mkdir(parents=True, exist_ok=True)
        joblib.dump(self, path)
        self.logger.info("Saved %s to %s", type(self).__name__, path)
        return path

    def load_model(self, filepath: Union[str, Path]) -> _BaseEnsemble:
        """Restore a persisted ensemble *into this instance*.

        Args:
            filepath: Path produced by :meth:`save_model`.

        Returns:
            ``self`` with parameters and fitted state replaced by the stored ones.

        Raises:
            FileNotFoundError: If ``filepath`` does not exist.
            TypeError: If the stored object is not an instance of this class.
        """
        path = Path(filepath)
        if not path.exists():
            raise FileNotFoundError(f"No saved model at {path}")
        loaded = joblib.load(path)
        if not isinstance(loaded, type(self)):
            raise TypeError(f"Expected a {type(self).__name__} in {path}, found {type(loaded).__name__}.")
        self.__dict__.clear()
        self.__dict__.update(loaded.__dict__)
        self.logger.info("Loaded %s from %s", type(self).__name__, path)
        return self

    @classmethod
    def load(cls, filepath: Union[str, Path]) -> _BaseEnsemble:
        """Load a persisted ensemble as a new instance."""
        instance = cls.__new__(cls)
        return instance.load_model(filepath)


# --------------------------------------------------------------------------- #
# Voting
# --------------------------------------------------------------------------- #
class VotingEnsemble(_BaseEnsemble):
    """Majority-vote / probability-averaging ensemble of heterogeneous estimators.

    For classification, ``voting="hard"`` performs (weighted) majority voting on
    predicted labels and ``voting="soft"`` averages predicted probabilities. For
    regression both settings average the predictions.

    Args:
        estimators: List of ``(name, estimator)`` pairs. All must be classifiers
            or all regressors.
        voting: ``"hard"`` or ``"soft"``.
        weights: Optional per-estimator weights (same length as ``estimators``).
        n_jobs: Number of parallel jobs for fitting the base estimators.
        task_type: ``"auto"`` (inferred from the estimators), ``"classification"``
            or ``"regression"``.
        verbose: Log per-estimator fitting progress.

    Attributes:
        estimators_: Fitted clones of the base estimators.
        named_estimators_: Mapping from name to fitted estimator.
        classes_: Class labels (classification only).
        task_type_: Resolved task type.
        n_features_in_: Number of input features.

    Example:
        >>> ensemble = VotingEnsemble([("rf", RandomForestClassifier()), ("lr", LogisticRegression())],
        ...                           voting="soft")
        >>> ensemble.fit(X_train, y_train).predict(X_test)
    """

    def __init__(
        self,
        estimators: EstimatorList,
        voting: str = "hard",
        weights: Optional[Sequence[float]] = None,
        n_jobs: Optional[int] = None,
        task_type: str = AUTO,
        verbose: bool = False,
    ) -> None:
        self.estimators = estimators
        self.voting = voting
        self.weights = weights
        self.n_jobs = n_jobs
        self.task_type = task_type
        self.verbose = verbose

    def _tag_estimators(self) -> Sequence[Any]:
        return [est for _, est in (self.estimators or [])]

    # ------------------------------------------------------------------ #
    def fit(self, X: ArrayLike, y: ArrayLike, sample_weight: Optional[ArrayLike] = None) -> VotingEnsemble:
        """Fit every base estimator on ``(X, y)``.

        Args:
            X: Feature matrix of shape ``(n_samples, n_features)``.
            y: Target vector.
            sample_weight: Optional sample weights forwarded to estimators that support them.

        Returns:
            The fitted ensemble.

        Raises:
            ValueError: If ``estimators`` is empty, mixes classifiers and regressors,
                ``voting`` is invalid, or soft voting is requested for estimators
                without ``predict_proba``.
        """
        if self.voting not in ("hard", "soft"):
            raise ValueError(f"voting must be 'hard' or 'soft', got {self.voting!r}.")
        estimators = _validate_estimators(self.estimators)
        X, y = _check_X_y(X, y)
        self.task_type_ = _resolve_task_type(self.task_type, [est for _, est in estimators], y)
        if self.task_type_ == CLASSIFICATION:
            if not all(is_classifier(est) for _, est in estimators):
                raise ValueError("All estimators must be classifiers for a classification VotingEnsemble.")
            if self.voting == "soft":
                missing = [name for name, est in estimators if not hasattr(est, "predict_proba")]
                if missing:
                    raise ValueError(f"Soft voting requires predict_proba; missing for {missing}.")
        elif not all(is_regressor(est) for _, est in estimators):
            raise ValueError("All estimators must be regressors for a regression VotingEnsemble.")

        weights = self._weights(len(estimators))
        if sample_weight is not None:
            sample_weight = column_or_1d(sample_weight)
            check_consistent_length(X, sample_weight)

        if self.task_type_ == CLASSIFICATION:
            self.le_ = LabelEncoder().fit(y)
            self.classes_ = self.le_.classes_

        if self.verbose:
            self.logger.info("Fitting %d estimators (%s voting)", len(estimators), self.voting)
        fitted = Parallel(n_jobs=self.n_jobs)(
            delayed(_fit_one)(clone(est), X, y, sample_weight) for _, est in estimators
        )
        self.estimators_ = list(fitted)
        self.named_estimators_ = {name: est for (name, _), est in zip(estimators, self.estimators_)}
        self.weights_ = weights
        self.n_features_in_ = X.shape[1]
        return self

    def _weights(self, n_estimators: int) -> np.ndarray:
        if self.weights is None:
            return np.ones(n_estimators, dtype=float)
        weights = np.asarray(self.weights, dtype=float)
        if weights.shape != (n_estimators,):
            raise ValueError(f"weights must have length {n_estimators}, got shape {weights.shape}.")
        if np.any(weights < 0) or not np.any(weights > 0):
            raise ValueError("weights must be non-negative with at least one positive entry.")
        return weights

    # ------------------------------------------------------------------ #
    def get_individual_predictions(self, X: ArrayLike) -> List[np.ndarray]:
        """Predictions of every fitted base estimator.

        Args:
            X: Feature matrix.

        Returns:
            List (in ``estimators`` order) of prediction arrays of shape ``(n_samples,)``.
        """
        check_is_fitted(self, "estimators_")
        X = _check_X(X)
        return [np.asarray(est.predict(X)) for est in self.estimators_]

    def get_individual_probabilities(self, X: ArrayLike) -> List[np.ndarray]:
        """Class probabilities of every fitted base estimator (classification only)."""
        check_is_fitted(self, "estimators_")
        if not self.is_classification_:
            raise AttributeError("Probabilities are only available for classification ensembles.")
        X = _check_X(X)
        return [np.asarray(est.predict_proba(X)) for est in self.estimators_]

    def transform(self, X: ArrayLike) -> np.ndarray:
        """Stack the individual predictions into an ``(n_samples, n_estimators)`` matrix."""
        return np.column_stack(self.get_individual_predictions(X))

    def predict_proba(self, X: ArrayLike) -> np.ndarray:
        """Weighted average of the base estimators' class probabilities.

        Args:
            X: Feature matrix.

        Returns:
            Array of shape ``(n_samples, n_classes)`` whose rows sum to one.

        Raises:
            AttributeError: For regression ensembles or when a base estimator lacks ``predict_proba``.
        """
        probas = self.get_individual_probabilities(X)
        return np.average(np.stack(probas, axis=0), axis=0, weights=self.weights_)

    def predict(self, X: ArrayLike) -> np.ndarray:
        """Aggregate the base predictions according to ``voting``.

        Args:
            X: Feature matrix.

        Returns:
            Predicted labels (classification) or values (regression).
        """
        check_is_fitted(self, "estimators_")
        if not self.is_classification_:
            preds = np.column_stack(self.get_individual_predictions(X)).astype(np.float64)
            return np.average(preds, axis=1, weights=self.weights_)
        if self.voting == "soft":
            return self.classes_[np.argmax(self.predict_proba(X), axis=1)]
        encoded = [self.le_.transform(p) for p in self.get_individual_predictions(X)]
        n_samples = len(encoded[0])
        votes = np.zeros((n_samples, len(self.classes_)), dtype=float)
        rows = np.arange(n_samples)
        for weight, pred in zip(self.weights_, encoded):
            votes[rows, pred] += weight
        return self.le_.inverse_transform(np.argmax(votes, axis=1))

    def agreement_rate(self, X: ArrayLike) -> float:
        """Fraction of samples on which *all* base estimators produce the same prediction."""
        return agreement_rate(self.get_individual_predictions(X))


# --------------------------------------------------------------------------- #
# Bagging
# --------------------------------------------------------------------------- #
class BaggingEnsemble(_BaseEnsemble):
    """Bootstrap-aggregating ensemble of a single base learner.

    Thin, task-aware wrapper around :class:`sklearn.ensemble.BaggingClassifier`
    / :class:`sklearn.ensemble.BaggingRegressor` that adds out-of-bag score
    access and per-member predictions.

    Args:
        base_estimator: Estimator to replicate. Defaults to a decision tree of the
            appropriate kind.
        n_estimators: Number of bootstrap replicas.
        max_samples: Fraction (float) or count (int) of samples drawn per replica.
        max_features: Fraction (float) or count (int) of features drawn per replica.
        bootstrap: Draw samples with replacement.
        bootstrap_features: Draw features with replacement.
        oob_score: Compute the out-of-bag generalisation estimate.
        n_jobs: Parallel jobs for fitting/predicting.
        random_state: Seed controlling the bootstrap draws.
        task_type: ``"auto"`` (inferred from ``base_estimator`` or ``y``), ``"classification"``
            or ``"regression"``.
        verbose: Verbosity forwarded to the scikit-learn bagging estimator.

    Attributes:
        ensemble_: The fitted scikit-learn bagging estimator.
        estimators_: Fitted replicas.
        estimators_features_: Feature indices used by each replica.
        oob_score_: Out-of-bag score (when ``oob_score=True``).
        classes_: Class labels (classification only).
        task_type_: Resolved task type.
    """

    def __init__(
        self,
        base_estimator: Optional[BaseEstimator] = None,
        n_estimators: int = 10,
        max_samples: Union[int, float] = 1.0,
        max_features: Union[int, float] = 1.0,
        bootstrap: bool = True,
        bootstrap_features: bool = False,
        oob_score: bool = False,
        n_jobs: Optional[int] = None,
        random_state: Optional[int] = None,
        task_type: str = AUTO,
        verbose: int = 0,
    ) -> None:
        self.base_estimator = base_estimator
        self.n_estimators = n_estimators
        self.max_samples = max_samples
        self.max_features = max_features
        self.bootstrap = bootstrap
        self.bootstrap_features = bootstrap_features
        self.oob_score = oob_score
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.task_type = task_type
        self.verbose = verbose

    def _tag_estimators(self) -> Sequence[Any]:
        return [self.base_estimator] if self.base_estimator is not None else []

    def fit(self, X: ArrayLike, y: ArrayLike, sample_weight: Optional[ArrayLike] = None) -> BaggingEnsemble:
        """Fit the bagging ensemble.

        Args:
            X: Feature matrix.
            y: Target vector.
            sample_weight: Optional sample weights.

        Returns:
            The fitted ensemble.

        Raises:
            ValueError: If ``n_estimators`` is not positive or the base estimator's task
                conflicts with ``task_type``.
        """
        if self.n_estimators < 1:
            raise ValueError(f"n_estimators must be >= 1, got {self.n_estimators}.")
        X, y = _check_X_y(X, y)
        self.task_type_ = _resolve_task_type(self.task_type, self._tag_estimators(), y)
        if self.base_estimator is None:
            base = (
                DecisionTreeClassifier(random_state=self.random_state)
                if self.task_type_ == CLASSIFICATION
                else DecisionTreeRegressor(random_state=self.random_state)
            )
        else:
            base = clone(self.base_estimator)
        bagging_cls = BaggingClassifier if self.task_type_ == CLASSIFICATION else BaggingRegressor
        params = dict(
            n_estimators=self.n_estimators,
            max_samples=self.max_samples,
            max_features=self.max_features,
            bootstrap=self.bootstrap,
            bootstrap_features=self.bootstrap_features,
            oob_score=self.oob_score,
            n_jobs=self.n_jobs,
            random_state=self.random_state,
            verbose=self.verbose,
        )
        params.update(_filter_kwargs(bagging_cls, {"estimator": base, "base_estimator": base}))
        self.ensemble_ = bagging_cls(**params)
        self.logger.debug("Fitting %s with %d estimators", bagging_cls.__name__, self.n_estimators)
        _fit_one(self.ensemble_, X, y, None if sample_weight is None else column_or_1d(sample_weight))
        self.base_estimator_ = base
        self.estimators_ = self.ensemble_.estimators_
        self.estimators_features_ = self.ensemble_.estimators_features_
        if self.task_type_ == CLASSIFICATION:
            self.classes_ = self.ensemble_.classes_
        if self.oob_score:
            self.oob_score_ = float(self.ensemble_.oob_score_)
        self.n_features_in_ = X.shape[1]
        return self

    def predict(self, X: ArrayLike) -> np.ndarray:
        """Aggregate predictions of all bootstrap replicas."""
        check_is_fitted(self, "ensemble_")
        return self.ensemble_.predict(_check_X(X))

    def predict_proba(self, X: ArrayLike) -> np.ndarray:
        """Averaged class probabilities (classification only)."""
        check_is_fitted(self, "ensemble_")
        if not self.is_classification_:
            raise AttributeError("predict_proba is only available for classification ensembles.")
        return self.ensemble_.predict_proba(_check_X(X))

    def get_oob_score(self) -> float:
        """Out-of-bag score computed during :meth:`fit`.

        Returns:
            OOB accuracy (classification) or R^2 (regression).

        Raises:
            ValueError: If the ensemble was built with ``oob_score=False``.
        """
        check_is_fitted(self, "ensemble_")
        if not self.oob_score:
            raise ValueError("Out-of-bag score is only available when oob_score=True.")
        return self.oob_score_

    def get_individual_predictions(self, X: ArrayLike) -> List[np.ndarray]:
        """Predictions of every bootstrap replica (on its own feature subset)."""
        check_is_fitted(self, "ensemble_")
        X = _check_X(X)
        preds: List[np.ndarray] = []
        for est, features in zip(self.estimators_, self.estimators_features_):
            pred = np.asarray(est.predict(X[:, features]))
            if self.task_type_ == CLASSIFICATION:
                pred = self.classes_[pred.astype(int)]
            preds.append(pred)
        return preds

    def get_feature_importance(self) -> np.ndarray:
        """Average ``feature_importances_`` over replicas that expose it.

        Returns:
            Importance vector of length ``n_features_in_`` (zero for never-sampled features).

        Raises:
            AttributeError: If the base estimator does not expose ``feature_importances_``.
        """
        check_is_fitted(self, "ensemble_")
        if not hasattr(self.estimators_[0], "feature_importances_"):
            raise AttributeError(f"{type(self.estimators_[0]).__name__} has no feature_importances_.")
        importance = np.zeros(self.n_features_in_, dtype=float)
        for est, features in zip(self.estimators_, self.estimators_features_):
            importance[features] += est.feature_importances_
        total = importance.sum()
        return importance / total if total > 0 else importance


# --------------------------------------------------------------------------- #
# Boosting
# --------------------------------------------------------------------------- #
class BoostingEnsemble(_BaseEnsemble):
    """Unified wrapper over the boosting family.

    Args:
        algorithm: One of ``"adaboost"``, ``"gradientboosting"``, ``"histgradientboosting"``,
            ``"xgboost"`` or ``"lightgbm"``. The last two require the optional dependency.
        n_estimators: Number of boosting rounds.
        learning_rate: Shrinkage; ``None`` keeps the library default.
        max_depth: Depth of the weak learners; ``None`` keeps the library default
            (ignored by AdaBoost, whose depth is set through ``base_estimator``).
        base_estimator: Weak learner for AdaBoost (defaults to a depth-1 tree).
        task_type: ``"auto"`` (inferred from ``y``), ``"classification"`` or ``"regression"``.
        random_state: Seed forwarded to the underlying estimator.
        n_jobs: Parallel jobs (XGBoost / LightGBM only).
        estimator_params: Extra keyword arguments forwarded to the underlying estimator.
            Unsupported keys are dropped with a warning.
        verbose: Verbosity level for the underlying estimator.

    Attributes:
        estimator_: The fitted boosting estimator.
        classes_: Class labels (classification only).
        feature_importances_: Impurity-based importances when available.
        task_type_: Resolved task type.
    """

    def __init__(
        self,
        algorithm: str = "gradientboosting",
        n_estimators: int = 100,
        learning_rate: Optional[float] = None,
        max_depth: Optional[int] = None,
        base_estimator: Optional[BaseEstimator] = None,
        task_type: str = AUTO,
        random_state: Optional[int] = None,
        n_jobs: Optional[int] = None,
        estimator_params: Optional[Dict[str, Any]] = None,
        verbose: int = 0,
    ) -> None:
        self.algorithm = algorithm
        self.n_estimators = n_estimators
        self.learning_rate = learning_rate
        self.max_depth = max_depth
        self.base_estimator = base_estimator
        self.task_type = task_type
        self.random_state = random_state
        self.n_jobs = n_jobs
        self.estimator_params = estimator_params
        self.verbose = verbose

    # ------------------------------------------------------------------ #
    def _build_estimator(self, task: str) -> BaseEstimator:
        """Instantiate the underlying boosting estimator for ``task``."""
        algorithm = str(self.algorithm).lower().replace("_", "").replace("-", "")
        if algorithm not in BOOSTING_ALGORITHMS:
            raise ValueError(f"algorithm must be one of {BOOSTING_ALGORITHMS}, got {self.algorithm!r}.")
        if self.n_estimators < 1:
            raise ValueError(f"n_estimators must be >= 1, got {self.n_estimators}.")
        is_clf = task == CLASSIFICATION
        params: Dict[str, Any] = {"random_state": self.random_state}
        if self.learning_rate is not None:
            params["learning_rate"] = self.learning_rate

        if algorithm == "adaboost":
            cls: Any = AdaBoostClassifier if is_clf else AdaBoostRegressor
            weak = self.base_estimator
            if weak is None and self.max_depth is not None:
                weak = (
                    DecisionTreeClassifier(max_depth=self.max_depth)
                    if is_clf
                    else DecisionTreeRegressor(max_depth=self.max_depth)
                )
            params["n_estimators"] = self.n_estimators
            if weak is not None:
                params.update(_filter_kwargs(cls, {"estimator": clone(weak), "base_estimator": clone(weak)}))
        elif algorithm == "gradientboosting":
            cls = GradientBoostingClassifier if is_clf else GradientBoostingRegressor
            params.update(n_estimators=self.n_estimators, verbose=self.verbose)
            if self.max_depth is not None:
                params["max_depth"] = self.max_depth
        elif algorithm == "histgradientboosting":
            cls = HistGradientBoostingClassifier if is_clf else HistGradientBoostingRegressor
            params.update(max_iter=self.n_estimators, verbose=self.verbose)
            if self.max_depth is not None:
                params["max_depth"] = self.max_depth
        elif algorithm == "xgboost":
            if not HAS_XGBOOST:
                raise ImportError("algorithm='xgboost' requires the optional dependency 'xgboost'.")
            cls = xgb.XGBClassifier if is_clf else xgb.XGBRegressor
            params.update(n_estimators=self.n_estimators, n_jobs=self.n_jobs, verbosity=min(self.verbose, 3))
            if self.max_depth is not None:
                params["max_depth"] = self.max_depth
        else:  # lightgbm
            if not HAS_LIGHTGBM:
                raise ImportError("algorithm='lightgbm' requires the optional dependency 'lightgbm'.")
            cls = lgb.LGBMClassifier if is_clf else lgb.LGBMRegressor
            params.update(n_estimators=self.n_estimators, n_jobs=self.n_jobs, verbose=self.verbose or -1)
            if self.max_depth is not None:
                params["max_depth"] = self.max_depth

        params.update(_filter_kwargs(cls, dict(self.estimator_params or {})))
        return cls(**_filter_kwargs(cls, params))

    @property
    def _algorithm(self) -> str:
        return str(self.algorithm).lower().replace("_", "").replace("-", "")

    # ------------------------------------------------------------------ #
    def fit(self, X: ArrayLike, y: ArrayLike, sample_weight: Optional[ArrayLike] = None) -> BoostingEnsemble:
        """Fit the boosting model.

        Args:
            X: Feature matrix.
            y: Target vector. Class labels are label-encoded internally so string
                targets work with every backend.
            sample_weight: Optional sample weights.

        Returns:
            The fitted ensemble.

        Raises:
            ValueError: For an unknown ``algorithm`` or invalid ``n_estimators``.
            ImportError: If an optional backend is requested but not installed.
        """
        X, y = _check_X_y(X, y)
        self.task_type_ = _validate_task_type(self.task_type)
        if self.task_type_ == AUTO:
            self.task_type_ = _target_task_type(y)
        self.estimator_ = self._build_estimator(self.task_type_)
        y_fit: np.ndarray = y
        if self.task_type_ == CLASSIFICATION:
            self.le_ = LabelEncoder().fit(y)
            self.classes_ = self.le_.classes_
            y_fit = self.le_.transform(y)
        self.logger.debug("Fitting %s (%s)", type(self.estimator_).__name__, self.task_type_)
        _fit_one(self.estimator_, X, y_fit, None if sample_weight is None else column_or_1d(sample_weight))
        if hasattr(self.estimator_, "feature_importances_"):
            self.feature_importances_ = np.asarray(self.estimator_.feature_importances_, dtype=float)
        self.n_features_in_ = X.shape[1]
        return self

    def _decode(self, pred: np.ndarray) -> np.ndarray:
        if self.task_type_ == CLASSIFICATION:
            return self.le_.inverse_transform(np.asarray(pred).astype(int))
        return np.asarray(pred, dtype=np.float64)

    def predict(self, X: ArrayLike) -> np.ndarray:
        """Predict labels or values."""
        check_is_fitted(self, "estimator_")
        return self._decode(self.estimator_.predict(_check_X(X)))

    def predict_proba(self, X: ArrayLike) -> np.ndarray:
        """Class probabilities (classification only)."""
        check_is_fitted(self, "estimator_")
        if not self.is_classification_:
            raise AttributeError("predict_proba is only available for classification ensembles.")
        return np.asarray(self.estimator_.predict_proba(_check_X(X)))

    def staged_predict(self, X: ArrayLike) -> Iterator[np.ndarray]:
        """Yield predictions after each boosting round.

        Args:
            X: Feature matrix.

        Yields:
            Prediction array of shape ``(n_samples,)`` for rounds ``1 .. n_rounds``.
        """
        check_is_fitted(self, "estimator_")
        X = _check_X(X)
        est = self.estimator_
        if hasattr(est, "staged_predict"):
            for pred in est.staged_predict(X):
                yield self._decode(pred)
            return
        n_rounds = self.get_n_rounds()
        for i in range(1, n_rounds + 1):
            if self._algorithm == "xgboost":
                yield self._decode(est.predict(X, iteration_range=(0, i)))
            else:  # lightgbm
                yield self._decode(est.predict(X, num_iteration=i))

    def get_n_rounds(self) -> int:
        """Number of boosting rounds actually fitted (early stopping aware)."""
        check_is_fitted(self, "estimator_")
        est = self.estimator_
        for attr in ("n_estimators_", "n_iter_"):
            if hasattr(est, attr):
                return int(getattr(est, attr))
        if hasattr(est, "estimators_"):
            return len(est.estimators_)
        if hasattr(est, "get_booster"):  # xgboost
            return int(est.get_booster().num_boosted_rounds())
        if hasattr(est, "booster_"):  # lightgbm
            return int(est.booster_.current_iteration())
        return int(self.n_estimators)

    def get_feature_importance(self) -> np.ndarray:
        """Impurity/gain-based feature importances of the fitted model.

        Returns:
            Non-negative array of length ``n_features_in_``.

        Raises:
            AttributeError: If the backend does not expose ``feature_importances_``
                (e.g. histogram gradient boosting; use permutation importance instead).
        """
        check_is_fitted(self, "estimator_")
        if not hasattr(self, "feature_importances_"):
            raise AttributeError(
                f"{type(self.estimator_).__name__} does not expose feature_importances_; "
                "use sklearn.inspection.permutation_importance instead."
            )
        return self.feature_importances_


# --------------------------------------------------------------------------- #
# Stacking / blending
# --------------------------------------------------------------------------- #
class _StackedEnsembleBase(_BaseEnsemble):
    """Shared machinery for stacking and blending (meta-feature construction)."""

    base_estimators: EstimatorList
    meta_estimator: Optional[BaseEstimator]
    stack_method: str
    passthrough: bool
    n_jobs: Optional[int]

    def _tag_estimators(self) -> Sequence[Any]:
        return [est for _, est in (self.base_estimators or [])]

    def _resolve_stack_method(self, estimator: BaseEstimator, task: str) -> str:
        """Pick the prediction method used to build meta-features for ``estimator``."""
        method = self.stack_method
        if method == AUTO:
            if task == CLASSIFICATION and hasattr(estimator, "predict_proba"):
                return "predict_proba"
            if task == CLASSIFICATION and hasattr(estimator, "decision_function"):
                return "decision_function"
            return "predict"
        if method not in ("predict", "predict_proba", "decision_function"):
            raise ValueError(
                "stack_method must be 'auto', 'predict', 'predict_proba' or 'decision_function'."
            )
        if not hasattr(estimator, method):
            raise ValueError(f"{type(estimator).__name__} does not implement {method}().")
        return method

    def _default_meta_estimator(self, task: str) -> BaseEstimator:
        return LogisticRegression(max_iter=1000) if task == CLASSIFICATION else Ridge(alpha=1.0)

    def _as_meta_block(self, output: np.ndarray, method: str) -> np.ndarray:
        """Shape a base-estimator output into a 2-D meta-feature block."""
        output = np.asarray(output)
        if output.ndim == 1:
            if method == "predict" and self.task_type_ == CLASSIFICATION:
                output = self.le_.transform(output)  # class labels -> ordinal codes
            return output.reshape(-1, 1).astype(np.float64)
        if method == "predict_proba" and output.shape[1] == 2:
            return output[:, 1:2]  # binary: keep P(class 1) only
        return output.astype(np.float64)

    def _meta_features(self, X: Any, base_outputs: Sequence[np.ndarray]) -> Any:
        """Concatenate meta-feature blocks (plus raw features when ``passthrough``)."""
        blocks: List[Any] = [self._as_meta_block(out, m) for out, m in zip(base_outputs, self.stack_methods_)]
        if self.passthrough:
            blocks.append(X)
        return _hstack(blocks)

    def _base_outputs(self, X: Any) -> List[np.ndarray]:
        return [np.asarray(getattr(est, m)(X)) for est, m in zip(self.base_estimators_, self.stack_methods_)]

    def _finalise(self, X: Any, y: np.ndarray, meta_train: Any, y_meta: np.ndarray) -> None:
        """Fit the meta-estimator and record shared fitted attributes."""
        meta = (
            self.meta_estimator
            if self.meta_estimator is not None
            else self._default_meta_estimator(self.task_type_)
        )
        meta_task = _estimator_task_type(meta)
        if meta_task is not None and meta_task != self.task_type_:
            raise ValueError(
                f"meta_estimator is a {meta_task} estimator but the base estimators are {self.task_type_}."
            )
        self.meta_estimator_ = clone(meta).fit(meta_train, y_meta)
        self.named_base_estimators_ = dict(zip(self.base_names_, self.base_estimators_))
        if self.task_type_ == CLASSIFICATION:
            self.classes_ = self.le_.classes_
        self.n_features_in_ = X.shape[1]
        self.n_meta_features_in_ = meta_train.shape[1]

    # -- public API ---------------------------------------------------------- #
    def transform(self, X: ArrayLike) -> Any:
        """Meta-features produced by the fitted base estimators for ``X``."""
        check_is_fitted(self, "base_estimators_")
        X = _check_X(X)
        return self._meta_features(X, self._base_outputs(X))

    def get_base_predictions(self, X: ArrayLike) -> np.ndarray:
        """Point predictions of each base estimator.

        Args:
            X: Feature matrix.

        Returns:
            Array of shape ``(n_samples, n_base_estimators)``.
        """
        check_is_fitted(self, "base_estimators_")
        X = _check_X(X)
        return np.column_stack([np.asarray(est.predict(X)) for est in self.base_estimators_])

    def get_individual_predictions(self, X: ArrayLike) -> List[np.ndarray]:
        """Per-estimator predictions as a list (mirrors :meth:`VotingEnsemble.get_individual_predictions`)."""
        preds = self.get_base_predictions(X)
        return [preds[:, i] for i in range(preds.shape[1])]

    def get_feature_names_out(self, input_features: Optional[Sequence[str]] = None) -> np.ndarray:
        """Names of the meta-features returned by :meth:`transform`."""
        check_is_fitted(self, "base_estimators_")
        names: List[str] = []
        n_classes = len(getattr(self, "classes_", [])) if self.task_type_ == CLASSIFICATION else 0
        for name, method in zip(self.base_names_, self.stack_methods_):
            if method == "predict" or (method == "predict_proba" and n_classes == 2) or n_classes == 0:
                names.append(f"{name}_{method}" if method != "predict" else name)
            elif method == "predict_proba":
                names.extend(f"{name}_proba_{cls}" for cls in self.classes_)
            else:
                width = 1 if n_classes == 2 else n_classes
                names.extend(f"{name}_{method}_{i}" for i in range(width))
        if self.passthrough:
            if input_features is None:
                input_features = [f"x{i}" for i in range(self.n_features_in_)]
            names.extend(str(f) for f in input_features)
        return np.asarray(names, dtype=object)

    def predict(self, X: ArrayLike) -> np.ndarray:
        """Predict with the meta-estimator on the stacked meta-features."""
        check_is_fitted(self, "meta_estimator_")
        return np.asarray(self.meta_estimator_.predict(self.transform(X)))

    def predict_proba(self, X: ArrayLike) -> np.ndarray:
        """Meta-estimator class probabilities (classification only)."""
        check_is_fitted(self, "meta_estimator_")
        if not self.is_classification_:
            raise AttributeError("predict_proba is only available for classification ensembles.")
        return np.asarray(self.meta_estimator_.predict_proba(self.transform(X)))

    def decision_function(self, X: ArrayLike) -> np.ndarray:
        """Meta-estimator decision function (classification only)."""
        check_is_fitted(self, "meta_estimator_")
        if not self.is_classification_ or not hasattr(self.meta_estimator_, "decision_function"):
            raise AttributeError("decision_function is not available for this ensemble.")
        return np.asarray(self.meta_estimator_.decision_function(self.transform(X)))


class StackingEnsemble(_StackedEnsembleBase):
    """Stacked generalisation with cross-validated (out-of-fold) meta-features.

    Each base estimator is evaluated with ``cv``-fold cross-validation to obtain
    leak-free predictions for every training sample; the meta-estimator is then
    trained on these out-of-fold predictions. Finally the base estimators are
    refitted on the full training set for inference.

    Args:
        base_estimators: List of ``(name, estimator)`` pairs (level-0 models).
        meta_estimator: Level-1 model. Defaults to logistic regression / ridge.
        cv: Number of folds or a CV splitter. Integers use stratified folds for
            classification and are shuffled when ``random_state`` is given.
        stack_method: ``"auto"``, ``"predict"``, ``"predict_proba"`` or ``"decision_function"``.
            ``"auto"`` prefers probabilities for classifiers.
        passthrough: Append the original features to the meta-features.
        n_jobs: Parallel jobs for cross-validation and refitting.
        random_state: Seed used to shuffle the folds.
        task_type: ``"auto"`` (inferred from the estimators), ``"classification"`` or ``"regression"``.
        verbose: Log progress.

    Attributes:
        base_estimators_: Fitted level-0 estimators (refit on the full data).
        meta_estimator_: Fitted level-1 estimator.
        stack_methods_: Method used per base estimator.
        oof_meta_features_: Out-of-fold meta-feature matrix used to train the meta-estimator.
        classes_: Class labels (classification only).
    """

    def __init__(
        self,
        base_estimators: EstimatorList,
        meta_estimator: Optional[BaseEstimator] = None,
        cv: Any = 5,
        stack_method: str = AUTO,
        passthrough: bool = False,
        n_jobs: Optional[int] = None,
        random_state: Optional[int] = None,
        task_type: str = AUTO,
        verbose: bool = False,
    ) -> None:
        self.base_estimators = base_estimators
        self.meta_estimator = meta_estimator
        self.cv = cv
        self.stack_method = stack_method
        self.passthrough = passthrough
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.task_type = task_type
        self.verbose = verbose

    def _build_cv(self, y: np.ndarray, task: str) -> Any:
        if isinstance(self.cv, (int, np.integer)):
            if self.cv < 2:
                raise ValueError(f"cv must be >= 2, got {self.cv}.")
            shuffle = self.random_state is not None
            splitter = StratifiedKFold if task == CLASSIFICATION else KFold
            return splitter(
                n_splits=int(self.cv), shuffle=shuffle, random_state=self.random_state if shuffle else None
            )
        return check_cv(self.cv, y, classifier=task == CLASSIFICATION)

    def fit(self, X: ArrayLike, y: ArrayLike) -> StackingEnsemble:
        """Fit base estimators (out-of-fold and on the full data) and the meta-estimator.

        Args:
            X: Feature matrix.
            y: Target vector.

        Returns:
            The fitted ensemble.

        Raises:
            ValueError: If the estimator list is invalid, tasks conflict, or ``cv`` is invalid.
        """
        estimators = _validate_estimators(self.base_estimators, "base_estimators")
        X, y = _check_X_y(X, y)
        self.task_type_ = _resolve_task_type(self.task_type, [est for _, est in estimators], y)
        self.base_names_ = [name for name, _ in estimators]
        self.stack_methods_ = [self._resolve_stack_method(est, self.task_type_) for _, est in estimators]
        if self.task_type_ == CLASSIFICATION:
            self.le_ = LabelEncoder().fit(y)
        self.cv_ = self._build_cv(y, self.task_type_)

        if self.verbose:
            self.logger.info("Generating out-of-fold predictions for %d base estimators", len(estimators))
        oof = Parallel(n_jobs=self.n_jobs)(
            delayed(cross_val_predict)(clone(est), X, y, cv=self.cv_, method=method)
            for (_, est), method in zip(estimators, self.stack_methods_)
        )
        self.base_estimators_ = list(
            Parallel(n_jobs=self.n_jobs)(delayed(_fit_one)(clone(est), X, y, None) for _, est in estimators)
        )
        self.oof_meta_features_ = self._meta_features(X, list(oof))
        self._finalise(X, y, self.oof_meta_features_, y)
        return self


class BlendingEnsemble(_StackedEnsembleBase):
    """Stacked generalisation with a single hold-out split ("blending").

    The training data is split once; base estimators are fitted on the first
    part and their predictions on the held-out part become the meta-features
    for the meta-estimator. Cheaper than :class:`StackingEnsemble` at the cost
    of using less data for each level.

    Args:
        base_estimators: List of ``(name, estimator)`` pairs.
        meta_estimator: Level-1 model. Defaults to logistic regression / ridge.
        holdout_size: Fraction (``0 < holdout_size < 1``) of training samples reserved
            for fitting the meta-estimator.
        stack_method: See :class:`StackingEnsemble`.
        passthrough: Append the original features to the meta-features.
        refit_base: Refit the base estimators on the *full* training set after the
            meta-estimator has been trained. Default keeps the canonical hold-out fit.
        n_jobs: Parallel jobs for fitting base estimators.
        random_state: Seed for the hold-out split (stratified for classification).
        task_type: ``"auto"``, ``"classification"`` or ``"regression"``.
        verbose: Log progress.

    Attributes:
        base_estimators_: Fitted base estimators.
        meta_estimator_: Fitted meta-estimator.
        train_indices_: Indices used to fit the base estimators.
        holdout_indices_: Indices used to fit the meta-estimator.
        holdout_meta_features_: Meta-feature matrix built on the hold-out part.
    """

    def __init__(
        self,
        base_estimators: EstimatorList,
        meta_estimator: Optional[BaseEstimator] = None,
        holdout_size: float = 0.2,
        stack_method: str = AUTO,
        passthrough: bool = False,
        refit_base: bool = False,
        n_jobs: Optional[int] = None,
        random_state: Optional[int] = None,
        task_type: str = AUTO,
        verbose: bool = False,
    ) -> None:
        self.base_estimators = base_estimators
        self.meta_estimator = meta_estimator
        self.holdout_size = holdout_size
        self.stack_method = stack_method
        self.passthrough = passthrough
        self.refit_base = refit_base
        self.n_jobs = n_jobs
        self.random_state = random_state
        self.task_type = task_type
        self.verbose = verbose

    def fit(self, X: ArrayLike, y: ArrayLike) -> BlendingEnsemble:
        """Fit base estimators on the training part and the meta-estimator on the hold-out part.

        Args:
            X: Feature matrix.
            y: Target vector.

        Returns:
            The fitted ensemble.

        Raises:
            ValueError: If ``holdout_size`` is outside ``(0, 1)`` or the estimator list is invalid.
        """
        if not 0.0 < float(self.holdout_size) < 1.0:
            raise ValueError(f"holdout_size must be in (0, 1), got {self.holdout_size}.")
        estimators = _validate_estimators(self.base_estimators, "base_estimators")
        X, y = _check_X_y(X, y)
        self.task_type_ = _resolve_task_type(self.task_type, [est for _, est in estimators], y)
        self.base_names_ = [name for name, _ in estimators]
        self.stack_methods_ = [self._resolve_stack_method(est, self.task_type_) for _, est in estimators]
        if self.task_type_ == CLASSIFICATION:
            self.le_ = LabelEncoder().fit(y)

        indices = np.arange(X.shape[0])
        stratify = y if self.task_type_ == CLASSIFICATION else None
        try:
            train_idx, hold_idx = train_test_split(
                indices, test_size=self.holdout_size, random_state=self.random_state, stratify=stratify
            )
        except ValueError:  # too few members of a class to stratify
            train_idx, hold_idx = train_test_split(
                indices, test_size=self.holdout_size, random_state=self.random_state
            )
        self.train_indices_, self.holdout_indices_ = train_idx, hold_idx
        X_train, y_train = X[train_idx], y[train_idx]
        X_hold, y_hold = X[hold_idx], y[hold_idx]

        if self.verbose:
            self.logger.info("Blending: %d train / %d hold-out samples", len(train_idx), len(hold_idx))
        self.base_estimators_ = list(
            Parallel(n_jobs=self.n_jobs)(
                delayed(_fit_one)(clone(est), X_train, y_train, None) for _, est in estimators
            )
        )
        self.holdout_meta_features_ = self._meta_features(X_hold, self._base_outputs(X_hold))
        self._finalise(X, y, self.holdout_meta_features_, y_hold)
        if self.refit_base:
            self.base_estimators_ = list(
                Parallel(n_jobs=self.n_jobs)(
                    delayed(_fit_one)(clone(est), X, y, None) for _, est in estimators
                )
            )
            self.named_base_estimators_ = dict(zip(self.base_names_, self.base_estimators_))
        return self


# --------------------------------------------------------------------------- #
# Diversity measures
# --------------------------------------------------------------------------- #
def _oracle_counts(pred_a: ArrayLike, pred_b: ArrayLike, y_true: ArrayLike) -> Tuple[int, int, int, int]:
    """Return the (N11, N10, N01, N00) oracle-output contingency counts."""
    a = np.asarray(pred_a) == np.asarray(y_true)
    b = np.asarray(pred_b) == np.asarray(y_true)
    check_consistent_length(a, b)
    n11 = int(np.sum(a & b))
    n10 = int(np.sum(a & ~b))
    n01 = int(np.sum(~a & b))
    n00 = int(np.sum(~a & ~b))
    return n11, n10, n01, n00


def disagreement_measure(pred_a: ArrayLike, pred_b: ArrayLike) -> float:
    """Fraction of samples on which two predictors disagree (label-based, no oracle needed)."""
    a, b = np.asarray(pred_a), np.asarray(pred_b)
    check_consistent_length(a, b)
    return float(np.mean(a != b))


def q_statistic(pred_a: ArrayLike, pred_b: ArrayLike, y_true: ArrayLike) -> float:
    """Yule's Q-statistic between two predictors' correctness (``-1`` diverse, ``1`` identical).

    Returns ``0.0`` when the statistic is undefined.
    """
    n11, n10, n01, n00 = _oracle_counts(pred_a, pred_b, y_true)
    denom = n11 * n00 + n01 * n10
    return float((n11 * n00 - n01 * n10) / denom) if denom else 0.0


def correlation_coefficient(pred_a: ArrayLike, pred_b: ArrayLike, y_true: ArrayLike) -> float:
    """Phi correlation between the correctness indicators of two predictors."""
    n11, n10, n01, n00 = _oracle_counts(pred_a, pred_b, y_true)
    denom = np.sqrt(float((n11 + n10) * (n01 + n00) * (n11 + n01) * (n10 + n00)))
    return float((n11 * n00 - n01 * n10) / denom) if denom else 0.0


def double_fault_measure(pred_a: ArrayLike, pred_b: ArrayLike, y_true: ArrayLike) -> float:
    """Fraction of samples misclassified by *both* predictors (lower is more diverse)."""
    n11, n10, n01, n00 = _oracle_counts(pred_a, pred_b, y_true)
    total = n11 + n10 + n01 + n00
    return float(n00 / total) if total else 0.0


def agreement_rate(predictions: Sequence[ArrayLike]) -> float:
    """Fraction of samples on which every predictor in ``predictions`` agrees."""
    stacked = np.column_stack([np.asarray(p) for p in predictions])
    if stacked.shape[1] < 2:
        return 1.0
    return float(np.mean(np.all(stacked == stacked[:, [0]], axis=1)))


def kohavi_wolpert_variance(predictions: Sequence[ArrayLike], y_true: ArrayLike) -> float:
    """Kohavi-Wolpert variance of an ensemble (higher means more diverse)."""
    correct = np.column_stack([np.asarray(p) == np.asarray(y_true) for p in predictions]).astype(float)
    n_samples, n_models = correct.shape
    n_correct = correct.sum(axis=1)
    return float(np.sum(n_correct * (n_models - n_correct)) / (n_samples * n_models**2))


def entropy_measure(predictions: Sequence[ArrayLike], y_true: ArrayLike) -> float:
    """Kuncheva's entropy diversity measure in ``[0, 1]`` (``1`` = maximal disagreement)."""
    correct = np.column_stack([np.asarray(p) == np.asarray(y_true) for p in predictions]).astype(float)
    n_samples, n_models = correct.shape
    if n_models < 2:
        return 0.0
    n_correct = correct.sum(axis=1)
    scale = n_models - int(np.ceil(n_models / 2))
    return float(np.sum(np.minimum(n_correct, n_models - n_correct)) / (n_samples * scale))


def pairwise_diversity(pred_a: ArrayLike, pred_b: ArrayLike, y_true: ArrayLike) -> Dict[str, float]:
    """All pairwise diversity measures for two predictors.

    Args:
        pred_a: Predictions of the first model.
        pred_b: Predictions of the second model.
        y_true: Ground-truth labels.

    Returns:
        Dict with ``disagreement``, ``q_statistic``, ``correlation`` and ``double_fault``.
    """
    return {
        "disagreement": disagreement_measure(pred_a, pred_b),
        "q_statistic": q_statistic(pred_a, pred_b, y_true),
        "correlation": correlation_coefficient(pred_a, pred_b, y_true),
        "double_fault": double_fault_measure(pred_a, pred_b, y_true),
    }


def diversity_matrix(
    predictions: Sequence[ArrayLike], y_true: ArrayLike, measure: str = "disagreement"
) -> np.ndarray:
    """Symmetric ``(n_models, n_models)`` matrix of a pairwise diversity measure.

    Args:
        predictions: One prediction array per model.
        y_true: Ground-truth labels.
        measure: ``"disagreement"``, ``"q_statistic"``, ``"correlation"`` or ``"double_fault"``.

    Returns:
        Matrix whose diagonal is the measure of a model with itself.

    Raises:
        ValueError: For an unknown measure.
    """
    measures = {
        "disagreement": lambda a, b: disagreement_measure(a, b),
        "q_statistic": lambda a, b: q_statistic(a, b, y_true),
        "correlation": lambda a, b: correlation_coefficient(a, b, y_true),
        "double_fault": lambda a, b: double_fault_measure(a, b, y_true),
    }
    if measure not in measures:
        raise ValueError(f"measure must be one of {sorted(measures)}, got {measure!r}.")
    fn = measures[measure]
    n = len(predictions)
    matrix = np.zeros((n, n), dtype=float)
    for i in range(n):
        matrix[i, i] = fn(predictions[i], predictions[i])
        for j in range(i + 1, n):
            matrix[i, j] = matrix[j, i] = fn(predictions[i], predictions[j])
    return matrix


class EnsembleAnalyzer(LoggerMixin):
    """Quantify base-model diversity and the gain an ensemble obtains over its members.

    Args:
        task_type: ``"classification"`` (diversity measures are defined for
            labels) or ``"regression"`` (only prediction correlation and error
            statistics are reported).
    """

    PAIRWISE_MEASURES = ("disagreement", "q_statistic", "correlation", "double_fault")

    def __init__(self, task_type: str = CLASSIFICATION) -> None:
        if task_type not in (CLASSIFICATION, REGRESSION):
            raise ValueError(f"task_type must be 'classification' or 'regression', got {task_type!r}.")
        self.task_type = task_type

    @staticmethod
    def _normalise_models(models: Any) -> List[Tuple[str, Any]]:
        if isinstance(models, dict):
            return list(models.items())
        return _validate_estimators(models, "models")

    def get_predictions(self, models: Any, X: ArrayLike) -> Dict[str, np.ndarray]:
        """Predictions of already-fitted models as ``{name: predictions}``."""
        return {name: np.asarray(model.predict(X)) for name, model in self._normalise_models(models)}

    def calculate_diversity(
        self,
        models: Any,
        X: ArrayLike,
        y: ArrayLike,
        predictions: Optional[Dict[str, ArrayLike]] = None,
    ) -> Dict[str, Any]:
        """Compute pairwise and ensemble-level diversity statistics.

        Args:
            models: Fitted models as ``{name: model}`` or ``[(name, model), ...]``.
                Ignored when ``predictions`` is given.
            X: Feature matrix used to obtain predictions.
            y: Ground-truth targets.
            predictions: Optional pre-computed ``{name: predictions}`` to avoid re-predicting.

        Returns:
            Dict containing ``model_names``, ``individual_scores``, the mean of each pairwise
            measure (``disagreement``, ``q_statistics``, ``correlation``, ``double_fault``),
            the corresponding ``*_matrix`` entries, plus ``agreement_rate``,
            ``kohavi_wolpert_variance`` and ``entropy`` for classification.

        Raises:
            ValueError: If fewer than two models are provided.
        """
        preds = predictions if predictions is not None else self.get_predictions(models, X)
        names = list(preds.keys())
        if len(names) < 2:
            raise ValueError("Diversity analysis needs at least two models.")
        arrays = [np.asarray(preds[n]) for n in names]
        y = np.asarray(y)
        result: Dict[str, Any] = {"model_names": names}
        if self.task_type == CLASSIFICATION:
            result["individual_scores"] = {n: float(accuracy_score(y, p)) for n, p in zip(names, arrays)}
            upper = np.triu_indices(len(names), k=1)
            for measure in self.PAIRWISE_MEASURES:
                matrix = diversity_matrix(arrays, y, measure=measure)
                key = "q_statistics" if measure == "q_statistic" else measure
                result[key] = float(matrix[upper].mean())
                result[f"{measure}_matrix"] = matrix
            result["agreement_rate"] = agreement_rate(arrays)
            result["kohavi_wolpert_variance"] = kohavi_wolpert_variance(arrays, y)
            result["entropy"] = entropy_measure(arrays, y)
        else:
            stacked = np.column_stack(arrays).astype(float)
            result["individual_scores"] = {n: float(r2_score(y, p)) for n, p in zip(names, arrays)}
            corr = np.corrcoef(stacked, rowvar=False)
            corr = np.nan_to_num(np.atleast_2d(corr))
            upper = np.triu_indices(len(names), k=1)
            result["correlation"] = float(corr[upper].mean())
            result["correlation_matrix"] = corr
            errors = stacked - y.reshape(-1, 1)
            err_corr = np.nan_to_num(np.atleast_2d(np.corrcoef(errors, rowvar=False)))
            result["error_correlation"] = float(err_corr[upper].mean())
            result["error_correlation_matrix"] = err_corr
            result["prediction_spread"] = float(np.mean(np.std(stacked, axis=1)))
        self.logger.debug("Diversity computed for %d models", len(names))
        return result

    def analyze_ensemble(self, ensemble: Any, X: ArrayLike, y: ArrayLike) -> Dict[str, Any]:
        """Compare a fitted ensemble against its members.

        Args:
            ensemble: A fitted ensemble exposing ``predict`` and ``get_individual_predictions``.
            X: Feature matrix.
            y: Ground-truth targets.

        Returns:
            Dict with ``ensemble_score``, ``individual_scores``, ``best_individual_score``,
            ``ensemble_gain`` (ensemble minus best member) and the diversity statistics.

        Raises:
            AttributeError: If ``ensemble`` does not expose ``get_individual_predictions``.
        """
        if not hasattr(ensemble, "get_individual_predictions"):
            raise AttributeError("ensemble must implement get_individual_predictions(X).")
        members = ensemble.get_individual_predictions(X)
        names = self._member_names(ensemble, len(members))
        preds = dict(zip(names, (np.asarray(m) for m in members)))
        scorer = accuracy_score if self.task_type == CLASSIFICATION else r2_score
        ensemble_score = float(scorer(y, ensemble.predict(X)))
        individual = {n: float(scorer(y, p)) for n, p in preds.items()}
        best = max(individual.values())
        report: Dict[str, Any] = {
            "ensemble_score": ensemble_score,
            "individual_scores": individual,
            "best_individual_score": best,
            "ensemble_gain": ensemble_score - best,
        }
        if len(preds) >= 2:
            report["diversity"] = self.calculate_diversity(None, X, y, predictions=preds)
        return report

    @staticmethod
    def _member_names(ensemble: Any, n_members: int) -> List[str]:
        for attr in ("named_estimators_", "named_base_estimators_"):
            names = getattr(ensemble, attr, None)
            if names and len(names) == n_members:
                return list(names.keys())
        return [f"member_{i}" for i in range(n_members)]


# --------------------------------------------------------------------------- #
# Factory facade
# --------------------------------------------------------------------------- #
class EnsembleMethods(LoggerMixin):
    """Factory for pre-configured ensemble estimators.

    Every ``get_*`` method returns an *unfitted* estimator so it can be placed
    in pipelines, cross-validated or cloned. Extra keyword arguments are
    forwarded to the underlying estimator; unsupported ones are dropped with a
    warning rather than raising.

    Args:
        random_state: Default seed applied to every estimator that accepts one.
        n_jobs: Default parallelism applied to every estimator that accepts it.
    """

    def __init__(self, random_state: Optional[int] = None, n_jobs: Optional[int] = None) -> None:
        self.random_state = random_state
        self.n_jobs = n_jobs

    # -- defaults ------------------------------------------------------------ #
    def _defaults(self, **overrides: Any) -> Dict[str, Any]:
        params: Dict[str, Any] = {"random_state": self.random_state, "n_jobs": self.n_jobs}
        params.update({k: v for k, v in overrides.items() if v is not None})
        return params

    def default_classifiers(self) -> List[Tuple[str, BaseEstimator]]:
        """Diverse default base classifiers (forest, logistic regression, shallow tree)."""
        rs = self.random_state
        return [
            ("rf", RandomForestClassifier(n_estimators=100, random_state=rs, n_jobs=self.n_jobs)),
            ("lr", LogisticRegression(max_iter=1000, random_state=rs)),
            ("dt", DecisionTreeClassifier(max_depth=5, random_state=rs)),
        ]

    def default_regressors(self) -> List[Tuple[str, BaseEstimator]]:
        """Diverse default base regressors (forest, linear, shallow tree)."""
        rs = self.random_state
        return [
            ("rf", RandomForestRegressor(n_estimators=100, random_state=rs, n_jobs=self.n_jobs)),
            ("lr", LinearRegression()),
            ("dt", DecisionTreeRegressor(max_depth=5, random_state=rs)),
        ]

    # -- voting -------------------------------------------------------------- #
    def get_voting_classifier(
        self,
        base_estimators: Optional[EstimatorList] = None,
        voting: str = "hard",
        weights: Optional[Sequence[float]] = None,
        n_jobs: Optional[int] = None,
    ) -> VotingEnsemble:
        """Voting classifier over ``base_estimators`` (defaults to :meth:`default_classifiers`)."""
        estimators = list(base_estimators) if base_estimators is not None else self.default_classifiers()
        return VotingEnsemble(
            estimators, voting=voting, weights=weights, n_jobs=n_jobs or self.n_jobs, task_type=CLASSIFICATION
        )

    def get_voting_regressor(
        self,
        estimators: Optional[EstimatorList] = None,
        weights: Optional[Sequence[float]] = None,
        n_jobs: Optional[int] = None,
    ) -> VotingEnsemble:
        """Averaging regressor over ``estimators`` (defaults to :meth:`default_regressors`)."""
        ests = list(estimators) if estimators is not None else self.default_regressors()
        return VotingEnsemble(
            ests, voting="soft", weights=weights, n_jobs=n_jobs or self.n_jobs, task_type=REGRESSION
        )

    # -- bagging ------------------------------------------------------------- #
    def get_bagging_classifier(
        self, base_estimator: Optional[BaseEstimator] = None, n_estimators: int = 100, **kwargs: Any
    ) -> BaggingEnsemble:
        """Bagging classifier (default base learner: decision tree)."""
        params = _filter_kwargs(BaggingEnsemble, self._defaults(**kwargs))
        return BaggingEnsemble(base_estimator, n_estimators=n_estimators, task_type=CLASSIFICATION, **params)

    def get_bagging_regressor(
        self, base_estimator: Optional[BaseEstimator] = None, n_estimators: int = 100, **kwargs: Any
    ) -> BaggingEnsemble:
        """Bagging regressor (default base learner: decision tree)."""
        params = _filter_kwargs(BaggingEnsemble, self._defaults(**kwargs))
        return BaggingEnsemble(base_estimator, n_estimators=n_estimators, task_type=REGRESSION, **params)

    def get_random_forest(
        self, task_type: str = CLASSIFICATION, n_estimators: int = 100, **kwargs: Any
    ) -> BaseEstimator:
        """Random forest for ``task_type``."""
        cls = RandomForestClassifier if task_type == CLASSIFICATION else RandomForestRegressor
        return cls(**_filter_kwargs(cls, self._defaults(n_estimators=n_estimators, **kwargs)))

    def get_extra_trees_classifier(self, n_estimators: int = 100, **kwargs: Any) -> ExtraTreesClassifier:
        """Extremely randomised trees classifier."""
        return ExtraTreesClassifier(
            **_filter_kwargs(ExtraTreesClassifier, self._defaults(n_estimators=n_estimators, **kwargs))
        )

    def get_extra_trees_regressor(self, n_estimators: int = 100, **kwargs: Any) -> ExtraTreesRegressor:
        """Extremely randomised trees regressor."""
        return ExtraTreesRegressor(
            **_filter_kwargs(ExtraTreesRegressor, self._defaults(n_estimators=n_estimators, **kwargs))
        )

    # -- boosting ------------------------------------------------------------ #
    def _boosting(
        self,
        algorithm: str,
        task_type: str,
        n_estimators: int,
        learning_rate: Optional[float],
        max_depth: Optional[int],
        base_estimator: Optional[BaseEstimator],
        kwargs: Dict[str, Any],
    ) -> BoostingEnsemble:
        random_state = kwargs.pop("random_state", self.random_state)
        n_jobs = kwargs.pop("n_jobs", self.n_jobs)
        return BoostingEnsemble(
            algorithm=algorithm,
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            base_estimator=base_estimator,
            task_type=task_type,
            random_state=random_state,
            n_jobs=n_jobs,
            estimator_params=kwargs or None,
        )

    def get_ada_boost_classifier(
        self,
        base_estimator: Optional[BaseEstimator] = None,
        n_estimators: int = 50,
        learning_rate: float = 1.0,
        **kwargs: Any,
    ) -> BoostingEnsemble:
        """AdaBoost classifier (default weak learner: decision stump)."""
        return self._boosting(
            "adaboost", CLASSIFICATION, n_estimators, learning_rate, None, base_estimator, kwargs
        )

    def get_ada_boost_regressor(
        self,
        base_estimator: Optional[BaseEstimator] = None,
        n_estimators: int = 50,
        learning_rate: float = 1.0,
        **kwargs: Any,
    ) -> BoostingEnsemble:
        """AdaBoost regressor."""
        return self._boosting(
            "adaboost", REGRESSION, n_estimators, learning_rate, None, base_estimator, kwargs
        )

    def get_gradient_boosting_classifier(
        self, n_estimators: int = 100, learning_rate: float = 0.1, max_depth: int = 3, **kwargs: Any
    ) -> BoostingEnsemble:
        """Gradient boosting classifier."""
        return self._boosting(
            "gradientboosting", CLASSIFICATION, n_estimators, learning_rate, max_depth, None, kwargs
        )

    def get_gradient_boosting_regressor(
        self, n_estimators: int = 100, learning_rate: float = 0.1, max_depth: int = 3, **kwargs: Any
    ) -> BoostingEnsemble:
        """Gradient boosting regressor."""
        return self._boosting(
            "gradientboosting", REGRESSION, n_estimators, learning_rate, max_depth, None, kwargs
        )

    def get_hist_gradient_boosting_classifier(
        self,
        n_estimators: int = 100,
        learning_rate: float = 0.1,
        max_depth: Optional[int] = None,
        **kwargs: Any,
    ) -> BoostingEnsemble:
        """Histogram-based gradient boosting classifier (native NaN support)."""
        return self._boosting(
            "histgradientboosting", CLASSIFICATION, n_estimators, learning_rate, max_depth, None, kwargs
        )

    def get_hist_gradient_boosting_regressor(
        self,
        n_estimators: int = 100,
        learning_rate: float = 0.1,
        max_depth: Optional[int] = None,
        **kwargs: Any,
    ) -> BoostingEnsemble:
        """Histogram-based gradient boosting regressor (native NaN support)."""
        return self._boosting(
            "histgradientboosting", REGRESSION, n_estimators, learning_rate, max_depth, None, kwargs
        )

    def get_xgboost_classifier(
        self, n_estimators: int = 100, learning_rate: float = 0.1, max_depth: int = 6, **kwargs: Any
    ) -> BoostingEnsemble:
        """XGBoost classifier (requires ``xgboost``)."""
        if not HAS_XGBOOST:
            raise ImportError("get_xgboost_classifier requires the optional dependency 'xgboost'.")
        return self._boosting("xgboost", CLASSIFICATION, n_estimators, learning_rate, max_depth, None, kwargs)

    def get_xgboost_regressor(
        self, n_estimators: int = 100, learning_rate: float = 0.1, max_depth: int = 6, **kwargs: Any
    ) -> BoostingEnsemble:
        """XGBoost regressor (requires ``xgboost``)."""
        if not HAS_XGBOOST:
            raise ImportError("get_xgboost_regressor requires the optional dependency 'xgboost'.")
        return self._boosting("xgboost", REGRESSION, n_estimators, learning_rate, max_depth, None, kwargs)

    def get_lightgbm_classifier(
        self, n_estimators: int = 100, learning_rate: float = 0.1, max_depth: int = -1, **kwargs: Any
    ) -> BoostingEnsemble:
        """LightGBM classifier (requires ``lightgbm``)."""
        if not HAS_LIGHTGBM:
            raise ImportError("get_lightgbm_classifier requires the optional dependency 'lightgbm'.")
        return self._boosting(
            "lightgbm", CLASSIFICATION, n_estimators, learning_rate, max_depth, None, kwargs
        )

    def get_lightgbm_regressor(
        self, n_estimators: int = 100, learning_rate: float = 0.1, max_depth: int = -1, **kwargs: Any
    ) -> BoostingEnsemble:
        """LightGBM regressor (requires ``lightgbm``)."""
        if not HAS_LIGHTGBM:
            raise ImportError("get_lightgbm_regressor requires the optional dependency 'lightgbm'.")
        return self._boosting("lightgbm", REGRESSION, n_estimators, learning_rate, max_depth, None, kwargs)

    # -- stacking / blending ------------------------------------------------- #
    def _stacking(
        self,
        task_type: str,
        level_0_estimators: Optional[EstimatorList],
        level_1_estimator: Optional[BaseEstimator],
        base_estimators: Optional[EstimatorList],
        final_estimator: Optional[BaseEstimator],
        cv: Any,
        stack_method: str,
        passthrough: bool,
        n_jobs: Optional[int],
    ) -> StackingEnsemble:
        bases = level_0_estimators if level_0_estimators is not None else base_estimators
        if bases is None:
            bases = self.default_classifiers() if task_type == CLASSIFICATION else self.default_regressors()
        meta = level_1_estimator if level_1_estimator is not None else final_estimator
        return StackingEnsemble(
            list(bases),
            meta_estimator=meta,
            cv=cv,
            stack_method=stack_method,
            passthrough=passthrough,
            n_jobs=n_jobs or self.n_jobs,
            random_state=self.random_state,
            task_type=task_type,
        )

    def get_stacking_classifier(
        self,
        level_0_estimators: Optional[EstimatorList] = None,
        level_1_estimator: Optional[BaseEstimator] = None,
        cv: Any = 5,
        stack_method: str = AUTO,
        n_jobs: Optional[int] = None,
        passthrough: bool = False,
        *,
        base_estimators: Optional[EstimatorList] = None,
        final_estimator: Optional[BaseEstimator] = None,
    ) -> StackingEnsemble:
        """Stacking classifier. ``base_estimators``/``final_estimator`` are accepted as aliases."""
        return self._stacking(
            CLASSIFICATION,
            level_0_estimators,
            level_1_estimator,
            base_estimators,
            final_estimator,
            cv,
            stack_method,
            passthrough,
            n_jobs,
        )

    def get_stacking_regressor(
        self,
        level_0_estimators: Optional[EstimatorList] = None,
        level_1_estimator: Optional[BaseEstimator] = None,
        cv: Any = 5,
        stack_method: str = AUTO,
        n_jobs: Optional[int] = None,
        passthrough: bool = False,
        *,
        base_estimators: Optional[EstimatorList] = None,
        final_estimator: Optional[BaseEstimator] = None,
    ) -> StackingEnsemble:
        """Stacking regressor. ``base_estimators``/``final_estimator`` are accepted as aliases."""
        return self._stacking(
            REGRESSION,
            level_0_estimators,
            level_1_estimator,
            base_estimators,
            final_estimator,
            cv,
            stack_method,
            passthrough,
            n_jobs,
        )

    def get_blending_classifier(
        self,
        base_estimators: Optional[EstimatorList] = None,
        meta_estimator: Optional[BaseEstimator] = None,
        holdout_size: float = 0.2,
        **kwargs: Any,
    ) -> BlendingEnsemble:
        """Blending classifier with a hold-out meta-training split."""
        bases = list(base_estimators) if base_estimators is not None else self.default_classifiers()
        params = _filter_kwargs(BlendingEnsemble, self._defaults(**kwargs))
        return BlendingEnsemble(
            bases, meta_estimator, holdout_size=holdout_size, task_type=CLASSIFICATION, **params
        )

    def get_blending_regressor(
        self,
        base_estimators: Optional[EstimatorList] = None,
        meta_estimator: Optional[BaseEstimator] = None,
        holdout_size: float = 0.2,
        **kwargs: Any,
    ) -> BlendingEnsemble:
        """Blending regressor with a hold-out meta-training split."""
        bases = list(base_estimators) if base_estimators is not None else self.default_regressors()
        params = _filter_kwargs(BlendingEnsemble, self._defaults(**kwargs))
        return BlendingEnsemble(
            bases, meta_estimator, holdout_size=holdout_size, task_type=REGRESSION, **params
        )

    def get_multi_level_stacking(
        self,
        level_0_estimators: EstimatorList,
        level_1_estimators: EstimatorList,
        level_2_estimator: Optional[BaseEstimator] = None,
        cv_folds: Sequence[int] = (5, 3),
        stack_methods: Sequence[str] = (AUTO, AUTO),
        task_type: str = CLASSIFICATION,
    ) -> StackingEnsemble:
        """Two-level stacking: each level-1 estimator stacks the level-0 pool, level-2 stacks those.

        Args:
            level_0_estimators: ``(name, estimator)`` pairs forming the base pool.
            level_1_estimators: ``(name, estimator)`` pairs, each used as the meta-learner of an
                independent :class:`StackingEnsemble` over the level-0 pool.
            level_2_estimator: Final meta-learner over the level-1 stacks.
            cv_folds: Folds used at level 0 and level 1 respectively.
            stack_methods: ``stack_method`` used at each level.
            task_type: ``"classification"`` or ``"regression"``.

        Returns:
            The (unfitted) nested :class:`StackingEnsemble`.
        """
        if len(cv_folds) != 2 or len(stack_methods) != 2:
            raise ValueError("cv_folds and stack_methods must each have exactly two entries.")
        level_0 = _validate_estimators(level_0_estimators, "level_0_estimators")
        level_1 = _validate_estimators(level_1_estimators, "level_1_estimators")
        inner = [
            (
                name,
                StackingEnsemble(
                    level_0,
                    meta_estimator=meta,
                    cv=cv_folds[0],
                    stack_method=stack_methods[0],
                    n_jobs=self.n_jobs,
                    random_state=self.random_state,
                    task_type=task_type,
                ),
            )
            for name, meta in level_1
        ]
        return StackingEnsemble(
            inner,
            meta_estimator=level_2_estimator,
            cv=cv_folds[1],
            stack_method=stack_methods[1],
            n_jobs=self.n_jobs,
            random_state=self.random_state,
            task_type=task_type,
        )

    # -- analysis ------------------------------------------------------------ #
    def get_analyzer(self, task_type: str = CLASSIFICATION) -> EnsembleAnalyzer:
        """Return an :class:`EnsembleAnalyzer` for ``task_type``."""
        return EnsembleAnalyzer(task_type=task_type)

    def compare_ensembles(
        self,
        ensembles: Union[Dict[str, Any], EstimatorList],
        X_train: ArrayLike,
        y_train: ArrayLike,
        X_test: ArrayLike,
        y_test: ArrayLike,
    ) -> Dict[str, float]:
        """Fit each ensemble on the training data and score it on the test data.

        Args:
            ensembles: ``{name: estimator}`` or ``[(name, estimator), ...]``.
            X_train: Training features.
            y_train: Training targets.
            X_test: Test features.
            y_test: Test targets.

        Returns:
            ``{name: test_score}`` using each estimator's own ``score`` method.
        """
        items = ensembles.items() if isinstance(ensembles, dict) else ensembles
        scores: Dict[str, float] = {}
        for name, estimator in items:
            model = clone(estimator).fit(X_train, y_train)
            scores[name] = float(model.score(X_test, y_test))
            self.logger.info("%s: test score %.4f", name, scores[name])
        return scores


__all__ = [
    "BOOSTING_ALGORITHMS",
    "HAS_LIGHTGBM",
    "HAS_XGBOOST",
    "BaggingEnsemble",
    "BlendingEnsemble",
    "BoostingEnsemble",
    "EnsembleAnalyzer",
    "EnsembleMethods",
    "StackingEnsemble",
    "VotingEnsemble",
    "agreement_rate",
    "correlation_coefficient",
    "disagreement_measure",
    "diversity_matrix",
    "double_fault_measure",
    "entropy_measure",
    "kohavi_wolpert_variance",
    "pairwise_diversity",
    "q_statistic",
]
