# File: mkdocs.yml
# Location: Project root directory

site_name: ML Pipeline Framework
site_description: Comprehensive machine learning pipeline framework with automated workflows
site_author: ML Team
site_url: https://SatvikPraveen.github.io/ml-pipeline-framework

repo_name: SatvikPraveen/ml-pipeline-framework
repo_url: https://github.com/SatvikPraveen/ml-pipeline-framework
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
  - mkdocs-jupyter:
      execute: false
      include_source: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - tables
  - footnotes

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - Getting Started:
      - Quick Start: tutorials/getting_started.md
      - Data Preprocessing: tutorials/data_preprocessing.md
      - Model Selection: tutorials/model_selection.md

  - Algorithm Guides:
      - Classification: algorithm_guides/classification.md
      - Regression: algorithm_guides/regression.md
      - Clustering: algorithm_guides/clustering.md
      - Ensemble Methods: algorithm_guides/ensemble_methods.md

  - API Reference:
      - Overview: api_reference/index.md
      - Models: api_reference/models.md
      - Data Processing: api_reference/data.md
      - Evaluation: api_reference/evaluation.md
      - Pipelines: api_reference/pipelines.md
      - Utilities: api_reference/utils.md

  - Advanced:
      - Troubleshooting: troubleshooting.md
      - FAQ: FAQ.md
      - Contributing: CONTRIBUTING.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SatvikPraveen/ml-pipeline-framework
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/ml-pipeline-framework
